version: 2

jobs:
  build-linux-arm-image:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login docker
          command: echo "$DOCKER_TOKEN" | docker login -u haohanyang --password-stdin
      - run:
          name: Build and push image
          command: docker buildx build --platform linux/arm64 -t haohanyang/node-docker-example-arm64:$CIRCLE_SHA1 -t haohanyang/node-docker-example-arm64:latest --push .

workflows:
  version: 2
  build-image:
    jobs:
      - build-linux-arm-image
