name: Build amd64 image

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: haohanyang
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: haohanyang/node-docker-example-amd64:${{ github.sha }},haohanyang/node-docker-example-amd64:latest
        platforms: linux/amd64